#Jekyll mastah-> webjeda - http://webjeda.com
#Author: 4
# Site settings
title: "ELMA 2017 - Program"
title-font-size: '3.2em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 5em.

email: elma2017@tu-sofia.bg
description: > # this means to ignore newlines until "baseurl:"
  Schedule for the XV-th International Conference on Electrical Machines, Drives and Power Systems ELMA2017.
base.url: http://bozhkoz.github.io # the subpath of your site, e.g. /blog
url: /schedule

permalink: :title/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 136
paginate_path: /page:num/


# Tracker
analytics: UA-98625202-1

# Comments
disqus-shortname: zhivkoz

# Contact form
# Go to http://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token: 18f43aff-a54b-4b9f-9084-e075509a4e78

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
