#Created by webjeda - http://webjeda.com

# Site settings
title: "ELMA 2017 - Program"
title-font-size: '4em' # a provision to adjust the size of your title. If it is too long then do resize to a smaller value. By default it will be 4em.

email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Post for the elma 2017 event.
base.url: https://bozhkoz.github.io # the subpath of your site, e.g. /blog
url: /schedule

permalink: :title/

# Build settings
markdown: kramdown
highlight: rouge
paginate: 99
paginate_path: /page:num/


# Tracker
analytics:

# Comments
disqus-shortname: webjeda-demo

# Contact form
# Go to https://getsimpleform.com and get a API token by signing up with your email and enter that here
api-token:

#CSS
sass:
  style: compressed


include: [_pages]

gems: [jekyll-paginate, jekyll-seo-tag]
